apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  default.yaml: |
    port: "3000"
    loglevel: info  
    persist: "true"
    mongodburl: mongodb://mongo-0.mongo:27017/echo?authSource=admin
    dbname: echo